### ISSUE TITLE
Assign to Flag and SourceComms intergration

### ISSUE THREAD

**Issue by SirConor** [neatek/GameVoting#4]
Would you be able to add ConVars for GameVoting to assign to certain flag
e.g.
// Who do you want to assign Gamevoting to? Set "0" for everyone or "Admin Flag" for certain admin flags
// -
// Default: "0"
gamevoting_voters "r"

And would you also be able to add Sourcecomms integration?

**Comment by neatek** [comment]
> // What admins you want to hide from voting? Set "0" or "" for display ALL admins. (def:'a')
> // -
> // Default: "a"
> gamevoting_admins_flag "a"

What about it?

# Dependence

I dont respect Sourcecomms. By the way, GameVoting using own style for mute and silence. I dont want to be dependent from other plugins, so, because i remove basecomm.smx and clientpref.smx dependence. Dependence from other plugins is problems, because if one plugin was broken, my plugin will not working, i dont want it.

**Comment by SirConor** [comment]
Yer I see your point of not wanting Dependence's on your plugin and with your reply to my first question gamevoting_admins_flag "a" < that removes admins with that flag from being targeted right? What i was asking was to be able to add a new Convar so rather than give gamevoting to everyone you can give it to people with certain admin flag so an example of it would of been what I posted

**Comment by neatek** [comment]
Do you want to add restrictions on voting? Some people which have some flag will be able to voting? Can you write it simple please) I am not good in english, but can understand most part.

**Comment by SirConor** [comment]
Yes, only people which have some flag will be able do to voting

**Comment by neatek** [comment]
So... please tell me, why this feature will be usefull?

**Comment by SirConor** [comment]
For me personally I would like it to be able to give my Community Members / donators Voting commands

**Comment by neatek** [comment]
## Feature №2

Flags for voting will be added. GameVoting 1.7.5.
**Now, please do hard tests Gv1.7.4 for detecting existed bugs**

**Comment by neatek** [comment]
## GameVoting 1.7.5-dev Pre-release

**Released**: https://forums.alliedmods.net/attachment.php?attachmentid=143002&d=1425809659
- Voteban reasons.
- Private flag.

**Comment by phaiz** [comment]
Just to add to your comment here -

"I dont respect Sourcecomms. By the way, GameVoting using own style for mute and silence. I dont want to be dependent from other plugins, so, because i remove basecomm.smx and clientpref.smx dependence. Dependence from other plugins is problems, because if one plugin was broken, my plugin will not working, i dont want it."

Integrating into Sourcecomms is very beneficial for server owners and their admins. Without this we are unable to see who is muted/gagged without giving access to the server logs. In addition to this, busy servers would have no efficient way of seeing how many times people have been muted/gagged without (again) handing out server access.
